---
- name: Configure EC2 instance for GitHub repo and Docker
  hosts: main_server
  become: true
  vars_files:
  - variables.yaml

  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
  
    - name: Install Docker
      become: true
      shell:
        cmd: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh ./get-docker.sh
      args:
        executable: /bin/bash

    - name: Install awscli
      become: true
      apt:
        name: awscli
        state: present

    - name: Install git
      become: true
      apt:
        name: git
        state: present

    - name: Clone GitHub repository
      become: true
      git:
        repo: https://github.com/ViniciusPilan/pdf-converter.git
        dest: /home/ubuntu/pdf-converter
 
    - name: Pull SSL cert and key
      become: true
      shell:
        cmd: |
          aws s3 cp s3://tools.vinipilan.com/letsencrypt-files/live/tools.vinipilan.com/fullchain.pem /home/vini/documents/projects/pdf-converter/to_deploy/certifications/pdf_converter.crt
          aws s3 cp s3://tools.vinipilan.com/letsencrypt-files/live/tools.vinipilan.com/privkey.pem /home/vini/documents/projects/pdf-converter/to_deploy/certifications/pdf_converter.key
      args:
        executable: /bin/bash

    - name: Start server
      become: true
      shell:
        cmd: |
          cd /home/vini/documents/projects/pdf-converter/to_deploy
          docker compose up -d
      args:
        executable: /bin/bash
        